name         'chrisboulton-nginx'
version      '0.0.1'
license      'MIT'
summary      'Install and manage nginx'
description  'A different approach to managing nginx sites available/enabled, and configuration includes.'
author       'Chris Boulton <chris@chrisboulton.com>'
source       'https://github.com/chrisboulton/puppet-nginx'
project_page 'https://github.com/chrisboulton/puppet-nginx'
